version: '3.8'

services:
  flask_app:
    build: .
    container_name: flask_app
    restart: always
    volumes:
      - ./honeypot_logs.log:/app/honeypot_logs.log
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask_app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge